# Generated by Django 4.1.4 on 2022-12-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0002_rename_horario_fun_atracao_horario_fun_fim_and_more'),
        ('core', '0002_alter_pontosturistico_aprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturistico',
            name='atracoes',
            field=models.ManyToManyField(to='atracoes.atracao'),
        ),
    ]
