# Generated by Django 4.1.4 on 2022-12-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('core', '0003_pontosturistico_atracoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturistico',
            name='comentarios',
            field=models.ManyToManyField(to='comentarios.comentario'),
        ),
    ]
