# Generated by Django 4.1.4 on 2022-12-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('core', '0004_pontosturistico_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturistico',
            name='avaliacoes',
            field=models.ManyToManyField(to='avaliacoes.avaliacao'),
        ),
    ]
