# Generated by Django 4.1.4 on 2022-12-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pontosturistico_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturistico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pontos_turisticos'),
        ),
    ]
