# Generated by Django 4.1.4 on 2022-12-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atracao',
            old_name='horario_fun',
            new_name='horario_fun_fim',
        ),
        migrations.AddField(
            model_name='atracao',
            name='horario_fun_inicio',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
